import type { Metadata } from "next";

import "@/styles/globals.css";

import { fontVariables } from "@/lib/fonts";
import Providers from "@/components/ui/core/providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       <html lang="en" suppressHydrationWarning>
      {/* <head>
        <script src="https://cdn.userway.org/widget.js" data-account="t85cN7BOL2"/>
        </head> */}
      <body
        className={`${fontVariables} antialiased `}
      >
        <Providers>
        {children}

        </Providers>
      </body>
    </html>
  );
}
